In [7]:
import numpy as np
import pandas as pd
from matplotlib import cm

dataset = pd.read_csv('dataset.csv')

X = dataset.iloc[:,0:3].values
print(X)
y = dataset.iloc[:,len(dataset.iloc[0])-1].values
print(y)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)


[[ 1.    2.    1.  ]
 [ 2.    3.    2.  ]
 [ 3.    4.    3.  ]
 [ 4.    5.    4.  ]
 [ 5.    6.    5.  ]
 [ 6.    7.    6.  ]
 [ 7.    8.    7.  ]
 [ 8.    9.    8.  ]
 [ 9.   10.    9.  ]
 [10.   11.   10.  ]
 [ 1.    2.1   1.1 ]
 [ 2.    3.1   2.1 ]
 [ 3.    4.1   3.1 ]
 [ 4.    5.1   4.1 ]
 [ 5.    6.1   5.1 ]
 [ 6.    7.1   6.1 ]
 [ 7.    8.1   7.1 ]
 [ 8.    9.1   8.1 ]
 [ 9.   10.1   9.1 ]
 [ 1.    2.5   1.5 ]
 [ 2.    3.5   2.5 ]
 [ 3.    4.5   3.5 ]
 [ 4.    5.5   4.5 ]
 [ 5.    7.5   5.5 ]
 [ 6.    8.5   7.5 ]
 [ 7.    9.5   8.5 ]
 [ 8.   10.5   9.5 ]
 [ 9.   11.5  10.5 ]
 [ 1.   12.5  11.5 ]
 [ 2.   13.5  12.5 ]
 [ 3.   14.5  13.5 ]
 [ 4.   15.5  14.5 ]
 [ 5.   16.5  15.5 ]
 [ 6.   17.5  16.5 ]
 [ 7.   18.5  17.5 ]
 [ 8.   20.5  18.5 ]
 [ 9.   21.5  20.5 ]
 [ 1.    2.    1.  ]
 [ 2.    3.    2.  ]
 [ 3.    4.    3.  ]
 [ 4.    7.    4.  ]
 [ 5.   13.    7.  ]
 [ 6.   14.   13.  ]
 [ 7.   15.   14.  ]
 [ 8.   16.   15.  ]
 [ 9.   17.   16.  ]
 [ 1.    2.11  1.11]
 [ 1.    5.11

In [4]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 7)
classifier.fit(X_train, y_train)

import pickle

pkl_filename = "pickle_model.pkl"
with open(pkl_filename, 'wb') as file:
    pickle.dump(classifier, file)

# Load from file
with open(pkl_filename, 'rb') as file:
    pickle_model = pickle.load(file)

y_test_pred = pickle_model.predict(X_test)

print(X_test)
print(y_test_pred)

[[ 1.    5.11  2.11]
 [ 5.    6.1   5.1 ]
 [ 8.    9.    8.  ]
 [ 6.    7.1   6.1 ]
 [ 5.    7.2   5.2 ]
 [ 6.    7.    6.  ]
 [ 6.    9.1   6.1 ]
 [ 1.    4.2   1.2 ]
 [ 6.   17.5  16.5 ]
 [ 5.    7.2   5.2 ]
 [ 7.    8.2   7.2 ]
 [ 7.    8.2   7.2 ]
 [ 6.    7.    6.  ]
 [ 3.    4.5   3.5 ]
 [ 4.    5.3   4.3 ]
 [ 8.   19.11 17.11]
 [ 9.   10.1   9.1 ]
 [ 2.    4.1   2.1 ]
 [ 3.    6.5   3.5 ]
 [ 1.    4.2   1.2 ]
 [ 2.    4.1   2.1 ]
 [ 4.    5.3   4.3 ]
 [ 1.    4.2   1.2 ]
 [ 9.   11.2  10.2 ]
 [ 9.   11.2  10.2 ]
 [ 5.    6.    5.  ]
 [ 8.   19.11 17.11]
 [ 3.    4.    3.  ]
 [ 8.   10.5   9.5 ]
 [ 4.   15.5  14.5 ]
 [ 2.    3.5   2.5 ]
 [ 8.   10.1   8.1 ]
 [ 1.    2.5   1.5 ]
 [ 8.   10.5   9.5 ]
 [ 1.    2.    1.  ]
 [ 6.   14.   13.  ]
 [ 4.    5.    4.  ]
 [ 9.   10.    9.  ]
 [ 9.   17.   16.  ]
 [ 4.    5.3   4.3 ]
 [ 8.   16.   15.  ]
 [ 6.    8.5   7.5 ]
 [ 9.   20.11 19.11]
 [ 6.    8.5   7.5 ]
 [ 3.   14.5  13.5 ]
 [ 7.    8.    7.  ]]
[1 2 3 2 2 2 2 1 2 2 2 2 2 1 1 2 

In [5]:
y_train_pred = classifier.predict(X_train)
y_test_pred = classifier.predict(X_test)

from sklearn.metrics import confusion_matrix
cm_train = confusion_matrix(y_train, y_train_pred)
cm_test = confusion_matrix(y_test, y_test_pred)

print("Training set confusion matrix : \n"+str(cm_train))
print("Success ratio on training set : "+str(success_ratio(cm=cm_train))+"%")
print("Test set confusion matrix : \n"+str(cm_test))
print("Success ratio on test set : "+str(success_ratio(cm=cm_test))+"%")

Training set confusion matrix : 
[[63  1  0]
 [ 4 39  2]
 [ 0  2 27]]
Success ratio on training set : 95.32710280373831%
Test set confusion matrix : 
[[17  1  0]
 [ 0 15  0]
 [ 0  4  9]]
Success ratio on test set : 96.96969696969697%
